domain_path: E:\Facultate\Anul_3\Semestrul_I\SSC\Vitis_polling_project_bin\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: E:\Vivado\Vitis\2024.1\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
